<?php
	
	namespace App\Database\Seeds;
	
	use App\Models\ChapterModel;
	use CodeIgniter\Database\Seeder;
	
	class Users extends Seeder
	{
		
		public function run()
		{
			$data = [
				'id' => '104462982366831663145',
				'name' => 'Quran Tazkia',
				'email' => 'quran@tazkia.ac.id',
				'photo' => 'https://lh4.googleusercontent.com/-bX7VywI3a_o/AAAAAAAAAAI/AAAAAAAAAAA/AMZuucl1RYTOnmaW5yodvyNH83Y85PGPYQ/s96-c/photo.jpg',
				'is_admin' => 'true',
				'status' => 'true',
				'created_at' => '2021-01-16 23:28:02',
				'updated_at' => '2021-01-16 23:28:02',
			];
			
			// Using Query Builder
			$this->db->table('users')->insert($data);
			
			
			$dataChapters = array(
				array(
					"id" => 1,
					"revelation_place" => "",
					"bismillah_pre" => "true",
					"name_complex" => "Al-Fātiĥah",
					"name_arabic" => "الفاتحة",
					"verses_count" => 7,
					"translated_name" => "Pembukaan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 2,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Baqarah",
					"name_arabic" => "البقرة",
					"verses_count" => 286,
					"translated_name" => "Sapi Betina",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 3,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Āli `Imrān",
					"name_arabic" => "آل عمران",
					"verses_count" => 200,
					"translated_name" => "Keluarga Imran",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 4,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "An-Nisā",
					"name_arabic" => "النساء",
					"verses_count" => 176,
					"translated_name" => "Wanita",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 5,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Mā'idah",
					"name_arabic" => "المائدة",
					"verses_count" => 120,
					"translated_name" => "Jamuan (Hidangan Makanan)",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 6,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-'An`ām",
					"name_arabic" => "الأنعام",
					"verses_count" => 165,
					"translated_name" => "Binatang Ternak",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 7,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-'A`rāf",
					"name_arabic" => "الأعراف",
					"verses_count" => 206,
					"translated_name" => "Tempat-tempat Tinggi",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 8,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-'Anfāl",
					"name_arabic" => "الأنفال",
					"verses_count" => 75,
					"translated_name" => "Rampasan Perang",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 9,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "At-Tawbah",
					"name_arabic" => "التوبة",
					"verses_count" => 129,
					"translated_name" => "Pengampunan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 10,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Yūnus",
					"name_arabic" => "يونس",
					"verses_count" => 109,
					"translated_name" => "Yunus",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 11,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Hūd",
					"name_arabic" => "هود",
					"verses_count" => 123,
					"translated_name" => "Hud",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 12,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Yūsuf",
					"name_arabic" => "يوسف",
					"verses_count" => 111,
					"translated_name" => "Yusuf",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 13,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Ar-Ra`d",
					"name_arabic" => "الرعد",
					"verses_count" => 43,
					"translated_name" => "Guruh (Petir)",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 14,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Ibrāhīm",
					"name_arabic" => "ابراهيم",
					"verses_count" => 52,
					"translated_name" => "Ibrahim",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 15,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Ĥijr",
					"name_arabic" => "الحجر",
					"verses_count" => 99,
					"translated_name" => "Bukit",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 16,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "An-Naĥl",
					"name_arabic" => "النحل",
					"verses_count" => 128,
					"translated_name" => "Lebah Madu",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 17,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-'Isrā",
					"name_arabic" => "الإسراء",
					"verses_count" => 111,
					"translated_name" => "Perjalanan Malam",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 18,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Kahf",
					"name_arabic" => "الكهف",
					"verses_count" => 110,
					"translated_name" => "Para Penghuni Gua",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 19,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Maryam",
					"name_arabic" => "مريم",
					"verses_count" => 98,
					"translated_name" => "Maryam",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 20,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Ţāhā",
					"name_arabic" => "طه",
					"verses_count" => 135,
					"translated_name" => "Tha-Ha",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 21,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-'Anbyā",
					"name_arabic" => "الأنبياء",
					"verses_count" => 112,
					"translated_name" => "Para Nabi",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 22,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Ĥajj",
					"name_arabic" => "الحج",
					"verses_count" => 78,
					"translated_name" => "Haji",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 23,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Mu'minūn",
					"name_arabic" => "المؤمنون",
					"verses_count" => 118,
					"translated_name" => "Orang-orang Mukmin",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 24,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "An-Nūr",
					"name_arabic" => "النور",
					"verses_count" => 64,
					"translated_name" => "Cahaya",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 25,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Furqān",
					"name_arabic" => "الفرقان",
					"verses_count" => 77,
					"translated_name" => "Pembeda",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 26,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Ash-Shu`arā",
					"name_arabic" => "الشعراء",
					"verses_count" => 227,
					"translated_name" => "Penyair",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 27,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "An-Naml",
					"name_arabic" => "النمل",
					"verses_count" => 93,
					"translated_name" => "Semut",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 28,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Qaşaş",
					"name_arabic" => "القصص",
					"verses_count" => 88,
					"translated_name" => "Kisah-kisah",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 29,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-`Ankabūt",
					"name_arabic" => "العنكبوت",
					"verses_count" => 69,
					"translated_name" => "Laba-laba",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 30,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Ar-Rūm",
					"name_arabic" => "الروم",
					"verses_count" => 60,
					"translated_name" => "Bangsa Romawi",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 31,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Luqmān",
					"name_arabic" => "لقمان",
					"verses_count" => 34,
					"translated_name" => "Luqman",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 32,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "As-Sajdah",
					"name_arabic" => "السجدة",
					"verses_count" => 30,
					"translated_name" => "Sujud",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 33,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-'Aĥzāb",
					"name_arabic" => "الأحزاب",
					"verses_count" => 73,
					"translated_name" => "Golongan yang Bersekutu",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 34,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Saba",
					"name_arabic" => "سبإ",
					"verses_count" => 54,
					"translated_name" => "Saba\'",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 35,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Fāţir",
					"name_arabic" => "فاطر",
					"verses_count" => 45,
					"translated_name" => "Pencipta",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 36,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Yā-Sīn",
					"name_arabic" => "يس",
					"verses_count" => 83,
					"translated_name" => "Yas Sin",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 37,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Aş-Şāffāt",
					"name_arabic" => "الصافات",
					"verses_count" => 182,
					"translated_name" => "Barisan-barisan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 38,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Şād",
					"name_arabic" => "ص",
					"verses_count" => 88,
					"translated_name" => "Shad",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 39,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Az-Zumar",
					"name_arabic" => "الزمر",
					"verses_count" => 75,
					"translated_name" => "Para Rombongan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 40,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Ghāfir",
					"name_arabic" => "غافر",
					"verses_count" => 85,
					"translated_name" => "Sang Maha Pengampun",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 41,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Fuşşilat",
					"name_arabic" => "فصلت",
					"verses_count" => 54,
					"translated_name" => "Yang Dijelaskan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 42,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Ash-Shūraá",
					"name_arabic" => "الشورى",
					"verses_count" => 53,
					"translated_name" => "Musyawarah",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 43,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Az-Zukhruf",
					"name_arabic" => "الزخرف",
					"verses_count" => 89,
					"translated_name" => "Perhiasan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 44,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Ad-Dukhān",
					"name_arabic" => "الدخان",
					"verses_count" => 59,
					"translated_name" => "Kabut",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 45,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Jāthiyah",
					"name_arabic" => "الجاثية",
					"verses_count" => 37,
					"translated_name" => "Yang Bertekuk Lutut",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 46,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-'Aĥqāf",
					"name_arabic" => "الأحقاف",
					"verses_count" => 35,
					"translated_name" => "Bukit-bukir Pasir",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 47,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Muĥammad",
					"name_arabic" => "محمد",
					"verses_count" => 38,
					"translated_name" => "Muhammad",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 48,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Fatĥ",
					"name_arabic" => "الفتح",
					"verses_count" => 29,
					"translated_name" => "Kemenangan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 49,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Ĥujurāt",
					"name_arabic" => "الحجرات",
					"verses_count" => 18,
					"translated_name" => "Kamar-kamar",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 50,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Qāf",
					"name_arabic" => "ق",
					"verses_count" => 45,
					"translated_name" => "Qaf",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 51,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Adh-Dhāriyāt",
					"name_arabic" => "الذاريات",
					"verses_count" => 60,
					"translated_name" => "Angin yang Menerbangkan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 52,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Aţ-Ţūr",
					"name_arabic" => "الطور",
					"verses_count" => 49,
					"translated_name" => "Bukit",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 53,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "An-Najm",
					"name_arabic" => "النجم",
					"verses_count" => 62,
					"translated_name" => "Bintang",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 54,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Qamar",
					"name_arabic" => "القمر",
					"verses_count" => 55,
					"translated_name" => "Bulan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 55,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Ar-Raĥmān",
					"name_arabic" => "الرحمن",
					"verses_count" => 78,
					"translated_name" => "Yang Maha Pemurah",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 56,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Wāqi`ah",
					"name_arabic" => "الواقعة",
					"verses_count" => 96,
					"translated_name" => "Hari Kiamat",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 57,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Ĥadīd",
					"name_arabic" => "الحديد",
					"verses_count" => 29,
					"translated_name" => "Besi",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 58,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Mujādila",
					"name_arabic" => "المجادلة",
					"verses_count" => 22,
					"translated_name" => "Wanita yang Menggugat",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 59,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Ĥashr",
					"name_arabic" => "الحشر",
					"verses_count" => 24,
					"translated_name" => "Pengusiran",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 60,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Mumtaĥanah",
					"name_arabic" => "الممتحنة",
					"verses_count" => 13,
					"translated_name" => "Wanita yang Diuji",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 61,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Aş-Şaf",
					"name_arabic" => "الصف",
					"verses_count" => 14,
					"translated_name" => "Barisan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 62,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Jumu`ah",
					"name_arabic" => "الجمعة",
					"verses_count" => 11,
					"translated_name" => "Hari Jum\'at",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 63,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Munāfiqūn",
					"name_arabic" => "المنافقون",
					"verses_count" => 11,
					"translated_name" => "Kaum Munafik",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 64,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "At-Taghābun",
					"name_arabic" => "التغابن",
					"verses_count" => 18,
					"translated_name" => "Hari Dinampakkan Kesalahan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 65,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Aţ-Ţalāq",
					"name_arabic" => "الطلاق",
					"verses_count" => 12,
					"translated_name" => "Perceraian",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 66,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "At-Taĥrīm",
					"name_arabic" => "التحريم",
					"verses_count" => 12,
					"translated_name" => "Mengharamkan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 67,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Mulk",
					"name_arabic" => "الملك",
					"verses_count" => 30,
					"translated_name" => "Kerajaan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 68,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Qalam",
					"name_arabic" => "القلم",
					"verses_count" => 52,
					"translated_name" => "Pena",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 69,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Ĥāqqah",
					"name_arabic" => "الحاقة",
					"verses_count" => 52,
					"translated_name" => "Kenyataan (Hari Kiamat)",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 70,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Ma`ārij",
					"name_arabic" => "المعارج",
					"verses_count" => 44,
					"translated_name" => "Tempat yang Naik",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 71,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Nūĥ",
					"name_arabic" => "نوح",
					"verses_count" => 28,
					"translated_name" => "Nuh",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 72,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Jinn",
					"name_arabic" => "الجن",
					"verses_count" => 28,
					"translated_name" => "Jin",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 73,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Muzzammil",
					"name_arabic" => "المزمل",
					"verses_count" => 20,
					"translated_name" => "Orang yang Berselimut",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 74,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Muddaththir",
					"name_arabic" => "المدثر",
					"verses_count" => 56,
					"translated_name" => "Orang yang Berkemul",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 75,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Qiyāmah",
					"name_arabic" => "القيامة",
					"verses_count" => 40,
					"translated_name" => "Hari Berbangkit",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 76,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-'Insān",
					"name_arabic" => "الانسان",
					"verses_count" => 31,
					"translated_name" => "Manusia",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 77,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Mursalāt",
					"name_arabic" => "المرسلات",
					"verses_count" => 50,
					"translated_name" => "Malaikat-malaikan yang Diutus",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 78,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "An-Naba",
					"name_arabic" => "النبإ",
					"verses_count" => 40,
					"translated_name" => "Berita Besar",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 79,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "An-Nāzi`āt",
					"name_arabic" => "النازعات",
					"verses_count" => 46,
					"translated_name" => "Malaikat yang Mencabut",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 80,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "`Abasa",
					"name_arabic" => "عبس",
					"verses_count" => 42,
					"translated_name" => "Ia Bermuka Masam",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 81,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "At-Takwīr",
					"name_arabic" => "التكوير",
					"verses_count" => 29,
					"translated_name" => "Menggulung",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 82,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-'Infiţār",
					"name_arabic" => "الإنفطار",
					"verses_count" => 19,
					"translated_name" => "Terbelah",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 83,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Muţaffifīn",
					"name_arabic" => "المطففين",
					"verses_count" => 36,
					"translated_name" => "Orang-orang Curang",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 84,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-'Inshiqāq",
					"name_arabic" => "الإنشقاق",
					"verses_count" => 25,
					"translated_name" => "Terbelah",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 85,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Burūj",
					"name_arabic" => "البروج",
					"verses_count" => 22,
					"translated_name" => "Gugusan Bintang",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 86,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Aţ-Ţāriq",
					"name_arabic" => "الطارق",
					"verses_count" => 17,
					"translated_name" => "Yang Datang di Malam Hari",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 87,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-'A`lá",
					"name_arabic" => "الأعلى",
					"verses_count" => 19,
					"translated_name" => "Yang Paling Tinggi",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 88,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Ghāshiyah",
					"name_arabic" => "الغاشية",
					"verses_count" => 26,
					"translated_name" => "Hari Pembalasan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 89,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Fajr",
					"name_arabic" => "الفجر",
					"verses_count" => 30,
					"translated_name" => "Fajar",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 90,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Balad",
					"name_arabic" => "البلد",
					"verses_count" => 20,
					"translated_name" => "Negeri",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 91,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Ash-Shams",
					"name_arabic" => "الشمس",
					"verses_count" => 15,
					"translated_name" => "Matahari",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 92,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Layl",
					"name_arabic" => "الليل",
					"verses_count" => 21,
					"translated_name" => "Malam",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 93,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Ađ-Đuĥaá",
					"name_arabic" => "الضحى",
					"verses_count" => 11,
					"translated_name" => "Waktu Dhuha",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 94,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Ash-Sharĥ",
					"name_arabic" => "الشرح",
					"verses_count" => 8,
					"translated_name" => "Melapangkan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 95,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "At-Tīn",
					"name_arabic" => "التين",
					"verses_count" => 8,
					"translated_name" => "Buah Tin",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 96,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-`Alaq",
					"name_arabic" => "العلق",
					"verses_count" => 19,
					"translated_name" => "Segumpal Darah",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 97,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Qadr",
					"name_arabic" => "القدر",
					"verses_count" => 5,
					"translated_name" => "Kemuliaan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 98,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Bayyinah",
					"name_arabic" => "البينة",
					"verses_count" => 8,
					"translated_name" => "Pembuktian",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 99,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Az-Zalzalah",
					"name_arabic" => "الزلزلة",
					"verses_count" => 8,
					"translated_name" => "Kegoncangan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 100,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-`Ādiyāt",
					"name_arabic" => "العاديات",
					"verses_count" => 11,
					"translated_name" => "Berlari Kencang",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 101,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Qāri`ah",
					"name_arabic" => "القارعة",
					"verses_count" => 11,
					"translated_name" => "Hari Kiamat",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 102,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "At-Takāthur",
					"name_arabic" => "التكاثر",
					"verses_count" => 8,
					"translated_name" => "Bermegah-megahan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 103,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-`Aşr",
					"name_arabic" => "العصر",
					"verses_count" => 3,
					"translated_name" => "Waktu Sore",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 104,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Humazah",
					"name_arabic" => "الهمزة",
					"verses_count" => 9,
					"translated_name" => "Pengumpat",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 105,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Fīl",
					"name_arabic" => "الفيل",
					"verses_count" => 5,
					"translated_name" => "Gajah",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 106,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Quraysh",
					"name_arabic" => "قريش",
					"verses_count" => 4,
					"translated_name" => "Suku Quraisy",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 107,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Mā`ūn",
					"name_arabic" => "الماعون",
					"verses_count" => 7,
					"translated_name" => "Barang yang Berguna",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 108,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Kawthar",
					"name_arabic" => "الكوثر",
					"verses_count" => 3,
					"translated_name" => "Nikmat Berlimpah",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 109,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Kāfirūn",
					"name_arabic" => "الكافرون",
					"verses_count" => 6,
					"translated_name" => "Orang-orang Kafir",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 110,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "An-Naşr",
					"name_arabic" => "النصر",
					"verses_count" => 3,
					"translated_name" => "Pertolongan",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 111,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Masad",
					"name_arabic" => "المسد",
					"verses_count" => 5,
					"translated_name" => "Gejolak Api (Sabut)",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 112,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-'Ikhlāş",
					"name_arabic" => "الإخلاص",
					"verses_count" => 4,
					"translated_name" => "Ikhlash",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 113,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "Al-Falaq",
					"name_arabic" => "الفلق",
					"verses_count" => 5,
					"translated_name" => "Waktu Shubuh",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"id" => 114,
					"revelation_place" => "",
					"bismillah_pre" => "false",
					"name_complex" => "An-Nās",
					"name_arabic" => "الناس",
					"verses_count" => 6,
					"translated_name" => "Umat Manusia",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => "")
			);
			foreach ($dataChapters as $row) {
				$data = array(
					'id' => $row['id'],
					'bismillah_pre' => $row['bismillah_pre'],
					'name_complex' => $row['name_complex'],
					'name_arabic' => $row['name_arabic'],
					'verses_count' => $row['verses_count'],
					'translated_name' => $row['translated_name'],
				);
				$this->db->table('chapters')->insert($data);
			}
			
			
			$dataTafsirResources = array(
				array(
					"name" => "Tafsir Ibnu Katsir",
					"author_name" => "Hafiz Ibn Kathir",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"name" => "Tafsir Muyassar",
					"author_name" => "Dr. Aidh Abdullah bin Aidh al-Qarni",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => ""),
				array(
					"name" => "Tafsir Jalalayn",
					"author_name" => "Jalal ad-Din al-Maḥalli",
					"created_at" => "2021-01-17 12:26:21",
					"updated_at" => "2021-01-17 12:26:21",
					"deleted_at" => "")
			);
			foreach ($dataTafsirResources as $row) {
				$this->db->table('tafsir_resource')->insert($row);
			}
			
			
		}
		
	}